[package]
name = "pi_path_finding"
version = "0.1.0"
authors = ["baip <baip@gmail.com>"]
edition = "2021"
description = "Path Finding Algorithm, such as A*, JPS"
repository = "https://github.com/GaiaWorld/pi_path_finding"
license = "MIT OR Apache-2.0"
keywords = ["pi", "path_finding", "A*", "JPS"]

[dependencies]
nalgebra = "0.30"
pi_heap = "0.1"
pi_null = "0.1"
num-traits = "0.2"
num-derive = "0.3"
bitvec = "1.0"

[dev-dependencies]
matrixcompare = "0.3"
rand_isaac = "0.3"
rand_xorshift = "0.3"
serde_json = "1.0"
raqote = "0.8"
pcg_rand = "0.13"
rand_core = "0.6"